### ISSUE TITLE
horizontal mouse rotate is always on world axes

### ISSUE THREAD

**Issue by ssfrr** [SimonDanisch/Makie.jl#38]
it seems that vertically rotating with the mouse up/down acts on the camera's coordinate system, but horizontal rotation (mouse left-right) is rotating along the world's axis. To me it seems like it would be more intuitive to have horizontal rotation also be around the camera's "up" axis, but I suppose this could be a subjective preference.

**Comment by SimonDanisch** [comment]
this might have been fixed by: https://github.com/JuliaGL/GLAbstraction.jl/commit/79cb6e3e37de112796d783c6dadc4ea3b23de944

**Comment by ssfrr** [comment]
just from looking at it, that seems like it would either rotate around (0, 0, 1) or (0, 0, -1) based on the camera angle. seems like it would be an improvement but you'd still have the behavior, e.g. if you're looking down from above and you drag left and right the scene would appear to rotate beneath you like the hand of a clock, rather than rotating relative to your viewpoint. I can play around with it a bit and maybe propose a PR you can try out and see if you like it better.

**Comment by SimonDanisch** [comment]
did you see https://github.com/JuliaGL/GLAbstraction.jl/issues/76 ?

**Comment by ssfrr** [comment]
Ah, I see. Looks like you’ve tried it and prefer the way it is. I’ll see if I get used to it and if I still like the other way maybe I’ll do a PR to make it configurable somehow
